<template>
  <div class="av-container">
    <form class="form">
      <label style="margin-bottom: 5px; font-weight: bold" for="create"
        >Player name</label
      >
      <input
        v-model="playerName"
        id="create"
        name="create"
        type="text"
        maxlength="20"
        autocomplete="off"
      />
      <div class="submit">
        <AvButton
          @click="createPlayer"
          :size="'large'"
          :source="'ico_create_player_submit'"
          :title="'Creates this player'"
          :name="'Submit'"
          :sound="'click'"
        ></AvButton>
        <AvButton
          @click="goBack"
          :size="'large'"
          :source="'ico_back_arrow'"
          :title="'Back to home'"
          :name="'Back'"
          :sound="'back'"
        ></AvButton>
      </div>
    </form>
  </div>
</template>

<script setup lang="ts">
import { defineProps, ref, inject, onMounted, defineEmits } from "vue";
import { HttpService } from "@/services/HttpService";
import { Authenticator, Players, SetQrCode } from "@/dtos/Dtos";
import AvButton from "@/components/small/AvButton.vue";

const updateAvText: any = inject("updateAvText");
const emit = defineEmits(["on-player-create"]);

const props = defineProps({
  gotoSibling: {
    type: Function,
  },
});

const playerName = ref<string>("");

const goBack = (): void => {
  updateAvText("Welcome back.");
  props.gotoSibling("");
};

const createPlayer = (): void => {
  if (playerName.value === "") {
    updateAvText(`You won't be able to play with a name like that.`);
    return;
  }

  const data = {
    name: playerName.value,
  };

  HttpService.httpPost("player/createplayer", data)
    .then((s) => s.json())
    .then((res: Authenticator) => {
      const setQrCode: SetQrCode = {
        playerName: playerName.value,
        qrCode: res.setupImage,
      };

      emit("on-player-create", setQrCode);
      playerName.value = "";
      props.gotoSibling("code");
    })
    .catch((err) => {
      updateAvText(err);
      return;
    });
};

const getPlayers = async () => {
  HttpService.httpGet("metadata/getplayers")
    .then((s) => s.json())
    .then((res: Players) => {
      updateAvText(
        "This application does not store personal or real player data. It does not deal with lost data either. \n" +
          "You create a player account with a given name, this name will be unique and a couple of characters long, i forgot how many, i think 20. \n" +
          "Once you choose a name a QR code will be displayed. Use Google authenticator to scan the code then proceed to login. \n" +
          "Your player identity will be this pair: your player name and the code generated by the authenticator app, this is how you will be able to walk inside the world of Av'el'Raan. \n" +
          `There are currently ${res.count} player accounts out of a maximum of 10.`
      );
    })
    .catch((err) => {
      updateAvText(err);
      return;
    });
};

onMounted(() => {
  getPlayers();
});
</script>

<style scoped>
.form {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
}
.submit {
  display: flex;
  justify-content: center;
  margin-top: 20px;
}
</style>
